/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsProyectoDAO;
import com.alee.extended.menu.WebDynamicMenu;
import conexion.clsConexionDS;
import java.awt.Window;
import java.sql.Connection;
import transferenciadatos.clsProyectoDTO;

/**
 *
 * @author Kevin
 */
public class frmArchivarProyecto extends javax.swing.JDialog {

    String proyectoId;
    private frmPrincipal objPrincipal;
    /**
     * Creates new form frmArchivarProyecto
     * @param parentWindow
     */
    public frmArchivarProyecto(Window parentWindow) {
        super(parentWindow);
        initComponents();
        this.setLocationRelativeTo(parentWindow);
        grupo.add(rbnFinalizado);
        grupo.add(rbnCancelado);
        grupo.add(rbnEspera);
        grupo.add(rbnOtro);
        
        rbnFinalizado.setSelected(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbnFinalizado = new javax.swing.JRadioButton();
        rbnCancelado = new javax.swing.JRadioButton();
        rbnEspera = new javax.swing.JRadioButton();
        rbnOtro = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnArchivarProyecto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Archivar Proyecto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 340));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(178, 223, 219));
        jPanel4.setMinimumSize(new java.awt.Dimension(650, 100));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel4.setText("¿Por qué se archivará el proyecto?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 240));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        rbnFinalizado.setBackground(new java.awt.Color(255, 255, 255));
        rbnFinalizado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnFinalizado.setText("Proyecto finalizado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 24);
        jPanel2.add(rbnFinalizado, gridBagConstraints);

        rbnCancelado.setBackground(new java.awt.Color(255, 255, 255));
        rbnCancelado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnCancelado.setText("Proyecto cancelado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 24);
        jPanel2.add(rbnCancelado, gridBagConstraints);

        rbnEspera.setBackground(new java.awt.Color(255, 255, 255));
        rbnEspera.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnEspera.setText("Proyecto en espera");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 24);
        jPanel2.add(rbnEspera, gridBagConstraints);

        rbnOtro.setBackground(new java.awt.Color(255, 255, 255));
        rbnOtro.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnOtro.setText("Otro motivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 24);
        jPanel2.add(rbnOtro, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Descripción breve:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 10, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        btnCancelar.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/cancel.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 24, 0);
        jPanel2.add(btnCancelar, gridBagConstraints);

        btnArchivarProyecto.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnArchivarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/archivar.png"))); // NOI18N
        btnArchivarProyecto.setText("ARCHIVAR PROYECTO");
        btnArchivarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivarProyectoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 24, 8);
        jPanel2.add(btnArchivarProyecto, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnArchivarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivarProyectoActionPerformed
        
        String estado = "";
        clsProyectoDTO proyectoDTO;
        clsProyectoDAO proyectoDAO = new clsProyectoDAO();
        Connection conexion;
        if(rbnFinalizado.isSelected())
        {
            estado = "finalizado";
        }
        else if(rbnCancelado.isSelected())
        {
            estado = "cancelado";
        }
        else if(rbnEspera.isSelected())
        {
            estado = "espera";
        }
        else if(rbnOtro.isSelected())
        {
            estado = "otro";
        }
        
        conexion = clsConexionDS.AbrirConexion();
        proyectoDTO = new clsProyectoDTO (
                        frmPrincipal.proyectoId,
                        estado,
                        txtDescripcion.getText(),
                        "",
                        "",
                        ""
                    );
        proyectoDAO.ActualizarEstadoProyecto(proyectoDTO, conexion);
        clsConexionDS.CerrarConexion(conexion);
        objPrincipal.AbrirModalProyectos();
        this.dispose();
        
    }//GEN-LAST:event_btnArchivarProyectoActionPerformed

    public void FormularioPrincipal(frmPrincipal xFormulario) {
       
        this.objPrincipal = xFormulario;
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivarProyecto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbnCancelado;
    private javax.swing.JRadioButton rbnEspera;
    private javax.swing.JRadioButton rbnFinalizado;
    private javax.swing.JRadioButton rbnOtro;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
