/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsCambioDAO;
import accesodatos.clsEvaluacionDAO;
import conexion.clsConexionDS;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import transferenciadatos.clsEvaluacionDTO;


/**
 * Esta clase implementa la creacion de un Nuevo Proyecto.
 * <p>
 * Esta operacion solo esta permitida a un usuario que sea Jefe de Proyecto.
 * @author Kevin
 */
public class frmCambioDerivado extends javax.swing.JPanel {
    
    ArrayList<String> arraySolicitudId = new ArrayList();
    ArrayList<String> arraySolicitudObjetivo = new ArrayList();
    ArrayList<String> arraySolicitudCliente = new ArrayList();
    ArrayList<String> arraySolicitudDescripcion = new ArrayList();
    
    ArrayList<String> arrayEvaluacionId = new ArrayList();
    ArrayList<String> arrayEvaluacionTipo = new ArrayList();
    ArrayList<String> arrayEvaluacionEncargado = new ArrayList();
    
    Connection conexion;
    
    /**
     * Creates new form frmNuevoProyecto
     */
    public frmCambioDerivado() {
        
        initComponents();        
        
        srpPrincipal.getVerticalScrollBar().setUnitIncrement(16);
        
        grupo.add(rbnLeve);
        grupo.add(rbnFuerte);
        rbnLeve.setSelected(true);
        
        conexion = clsConexionDS.AbrirConexion();
        CargarComboSolicitudCambioDerivada();
        clsConexionDS.CerrarConexion(conexion);
        
        int auxIndice = cmbSolicitud.getSelectedIndex();            
        txtSolicitudCliente.setText(arraySolicitudCliente.get(auxIndice));
        txtSolicitudObjetivo.setText(arraySolicitudObjetivo.get(auxIndice));
        txtSolicitudDescripcion.setText(arraySolicitudDescripcion.get(auxIndice));
        if(arrayEvaluacionTipo.get(auxIndice).equals("fuerte"))
        {
            rbnFuerte.setSelected(true);
        }
        else
        {
            rbnLeve.setSelected(true);
        }
        txtEvaluacionEncargado.setText(arrayEvaluacionEncargado.get(auxIndice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupo = new javax.swing.ButtonGroup();
        jSlider1 = new javax.swing.JSlider();
        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPrincipalPadre = new javax.swing.JPanel();
        srpPrincipal = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlTituloDatosGenerales = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSolicitudCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSolicitudDescripcion = new javax.swing.JTextArea();
        cmbSolicitud = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSolicitudObjetivo = new javax.swing.JTextField();
        pnlMetodologia = new javax.swing.JPanel();
        pnlMetodologiaProyectoTitlo = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlMetodologiaProyectoCuerpo = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEvaluacionJefe = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        btnEvaluarCambio = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JCheckBox();
        pnlEquipoProyecto = new javax.swing.JPanel();
        pnlEquipoProyectoTitlo = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlEquipoProyectoCuerpo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rbnLeve = new javax.swing.JRadioButton();
        rbnFuerte = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtEvaluacionEncargado = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(179, 229, 252));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("SOLICITUDES DE CAMBIO DERIVADAS");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        pnlTitulo.add(jPanel1, gridBagConstraints);

        add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlPrincipalPadre.setLayout(new java.awt.GridBagLayout());

        srpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        srpPrincipal.setBorder(null);

        pnlPrincipal.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(970, 510));
        jPanel3.setPreferredSize(new java.awt.Dimension(970, 510));
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnlTituloDatosGenerales.setBackground(new java.awt.Color(255, 255, 0));
        pnlTituloDatosGenerales.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlTituloDatosGenerales.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(jSeparator1, java.awt.BorderLayout.CENTER);

        pnlTituloDatosGenerales.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel4.setText("Datos generales de la solicitud");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        pnlTituloDatosGenerales.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(pnlTituloDatosGenerales, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(670, 341));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Cliente.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 300);
        jPanel6.add(jLabel1, gridBagConstraints);

        txtSolicitudCliente.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtSolicitudCliente.setMinimumSize(new java.awt.Dimension(10, 30));
        txtSolicitudCliente.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 0, 300);
        jPanel6.add(txtSolicitudCliente, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Descripción de la solicitud.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 300);
        jPanel6.add(jLabel6, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(264, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(264, 120));

        txtSolicitudDescripcion.setColumns(20);
        txtSolicitudDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtSolicitudDescripcion.setRows(5);
        txtSolicitudDescripcion.setMinimumSize(new java.awt.Dimension(264, 50));
        txtSolicitudDescripcion.setPreferredSize(new java.awt.Dimension(264, 80));
        jScrollPane1.setViewportView(txtSolicitudDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 35, 300);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        cmbSolicitud.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        cmbSolicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSolicitud.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSolicitudItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 300);
        jPanel6.add(cmbSolicitud, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel9.setText("Solicitudes de cambio derivadas.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 300);
        jPanel6.add(jLabel9, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Objetivo de la solicitud.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 300);
        jPanel6.add(jLabel3, gridBagConstraints);

        txtSolicitudObjetivo.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtSolicitudObjetivo.setMinimumSize(new java.awt.Dimension(10, 30));
        txtSolicitudObjetivo.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 0, 300);
        jPanel6.add(txtSolicitudObjetivo, gridBagConstraints);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(jPanel3, gridBagConstraints);

        pnlMetodologia.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologia.setMinimumSize(new java.awt.Dimension(970, 500));
        pnlMetodologia.setPreferredSize(new java.awt.Dimension(970, 500));
        pnlMetodologia.setLayout(new java.awt.BorderLayout());

        pnlMetodologiaProyectoTitlo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologiaProyectoTitlo.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlMetodologiaProyectoTitlo.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(jSeparator3, java.awt.BorderLayout.CENTER);

        pnlMetodologiaProyectoTitlo.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel10.setText("Evaluación del cambio.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(791, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(20, 20, 20))
        );

        pnlMetodologiaProyectoTitlo.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        pnlMetodologia.add(pnlMetodologiaProyectoTitlo, java.awt.BorderLayout.PAGE_START);

        pnlMetodologiaProyectoCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologiaProyectoCuerpo.setPreferredSize(new java.awt.Dimension(437, 500));
        pnlMetodologiaProyectoCuerpo.setLayout(new java.awt.GridBagLayout());

        jScrollPane5.setMinimumSize(new java.awt.Dimension(250, 120));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(250, 120));

        txtEvaluacionJefe.setColumns(20);
        txtEvaluacionJefe.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtEvaluacionJefe.setRows(5);
        txtEvaluacionJefe.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEvaluacionJefe.setMinimumSize(new java.awt.Dimension(250, 40));
        txtEvaluacionJefe.setPreferredSize(new java.awt.Dimension(250, 40));
        jScrollPane5.setViewportView(txtEvaluacionJefe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 300);
        pnlMetodologiaProyectoCuerpo.add(jScrollPane5, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel13.setText("Evaluación del cambio.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlMetodologiaProyectoCuerpo.add(jLabel13, gridBagConstraints);

        btnEvaluarCambio.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnEvaluarCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/rotate-3d.png"))); // NOI18N
        btnEvaluarCambio.setText("EVALUAR CAMBIO");
        btnEvaluarCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarCambioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(35, 200, 35, 50);
        pnlMetodologiaProyectoCuerpo.add(btnEvaluarCambio, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlMetodologiaProyectoCuerpo.add(jSeparator6, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel14.setText("Estado del cambio.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlMetodologiaProyectoCuerpo.add(jLabel14, gridBagConstraints);

        cbxEstado.setBackground(new java.awt.Color(255, 255, 255));
        cbxEstado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        cbxEstado.setText("Aprobado por el comité");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 24, 0);
        pnlMetodologiaProyectoCuerpo.add(cbxEstado, gridBagConstraints);

        pnlMetodologia.add(pnlMetodologiaProyectoCuerpo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPrincipal.add(pnlMetodologia, gridBagConstraints);

        pnlEquipoProyecto.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyecto.setMinimumSize(new java.awt.Dimension(585, 380));
        pnlEquipoProyecto.setPreferredSize(new java.awt.Dimension(970, 380));
        pnlEquipoProyecto.setLayout(new java.awt.BorderLayout());

        pnlEquipoProyectoTitlo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoTitlo.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlEquipoProyectoTitlo.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jSeparator2, java.awt.BorderLayout.CENTER);

        pnlEquipoProyectoTitlo.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel7.setText("Evaluación del encargado");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(769, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );

        pnlEquipoProyectoTitlo.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyecto.add(pnlEquipoProyectoTitlo, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyectoCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel12.setText("Tipo de cambio.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlEquipoProyectoCuerpo.add(jLabel12, gridBagConstraints);

        rbnLeve.setBackground(new java.awt.Color(255, 255, 255));
        rbnLeve.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnLeve.setText("Leve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 24);
        pnlEquipoProyectoCuerpo.add(rbnLeve, gridBagConstraints);

        rbnFuerte.setBackground(new java.awt.Color(255, 255, 255));
        rbnFuerte.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnFuerte.setText("Fuerte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlEquipoProyectoCuerpo.add(rbnFuerte, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel15.setText("Evaluación del encargado.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlEquipoProyectoCuerpo.add(jLabel15, gridBagConstraints);

        jScrollPane6.setMinimumSize(new java.awt.Dimension(250, 120));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(250, 120));

        txtEvaluacionEncargado.setColumns(20);
        txtEvaluacionEncargado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtEvaluacionEncargado.setRows(5);
        txtEvaluacionEncargado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEvaluacionEncargado.setMinimumSize(new java.awt.Dimension(250, 40));
        txtEvaluacionEncargado.setPreferredSize(new java.awt.Dimension(250, 40));
        jScrollPane6.setViewportView(txtEvaluacionEncargado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 35, 300);
        pnlEquipoProyectoCuerpo.add(jScrollPane6, gridBagConstraints);

        pnlEquipoProyecto.add(pnlEquipoProyectoCuerpo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(pnlEquipoProyecto, gridBagConstraints);

        srpPrincipal.setViewportView(pnlPrincipal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        pnlPrincipalPadre.add(srpPrincipal, gridBagConstraints);

        add(pnlPrincipalPadre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvaluarCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarCambioActionPerformed
        
        clsEvaluacionDAO evaluacionDAO;
        clsEvaluacionDTO evaluacionDTO;
        
        String evaluacionTipo = "";
        String evaluacionEncargado;
        String evaluacionJefe;
        String evaluacionEstado;
        String evaluacionId;
        String solicitudId;
        String mensaje;
        
        if(rbnLeve.isSelected())
        {
            evaluacionTipo = "leve";
        }
        else if(rbnFuerte.isSelected())
        {
            evaluacionTipo = "fuerte";
        }
        
        evaluacionEncargado = txtEvaluacionEncargado.getText();
        evaluacionJefe = txtEvaluacionJefe.getText();
        
        if(cbxEstado.isSelected())
        {
            evaluacionEstado = "1";
            mensaje = "Solicitud de cambio aprobada correctamente por el comité.";
        }
        else
        {
            evaluacionEstado = "0";
            mensaje = "La solicitud de cambio fue rechazada por el comité.";
        }
        
        solicitudId = arraySolicitudId.get(cmbSolicitud.getSelectedIndex());
        evaluacionId = arrayEvaluacionId.get(cmbSolicitud.getSelectedIndex());
        
        evaluacionDAO = new clsEvaluacionDAO();
        evaluacionDTO = new clsEvaluacionDTO (
                        evaluacionId,
                        evaluacionTipo,
                        evaluacionEncargado,
                        evaluacionJefe,
                        evaluacionEstado,
                        solicitudId
        );
        
        conexion = clsConexionDS.AbrirConexion();
        evaluacionDAO.ActualizarEvaluacion(evaluacionDTO, conexion);
        clsConexionDS.CerrarConexion(conexion);
        JOptionPane.showMessageDialog(this, mensaje, "Solicitud evaluada correctamente", 
                                    JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnEvaluarCambioActionPerformed

    private void cmbSolicitudItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSolicitudItemStateChanged
        
        if(cmbSolicitud.getSelectedIndex() != -1)
        {
            int auxIndice = cmbSolicitud.getSelectedIndex();
            
            txtSolicitudCliente.setText(arraySolicitudCliente.get(auxIndice));
            txtSolicitudObjetivo.setText(arraySolicitudObjetivo.get(auxIndice));
            txtSolicitudDescripcion.setText(arraySolicitudDescripcion.get(auxIndice));
        }
        
    }//GEN-LAST:event_cmbSolicitudItemStateChanged

    private void CargarComboSolicitudCambioDerivada() {
        
        DefaultComboBoxModel dcbmSolicitud;
        clsCambioDAO cambioDAO;
        ResultSet rsResultado;
        
        dcbmSolicitud = new DefaultComboBoxModel();
        cambioDAO = new clsCambioDAO();        
        rsResultado = cambioDAO.SeleccionarSolicitudCambioDerivada(conexion);
                        
        try 
        {
            while(rsResultado.next())
            {
                dcbmSolicitud.addElement (
                        rsResultado.getString("proyecto_nombre") + " - " +
                        rsResultado.getString("solicitud_fecha_format")
                );
                
                arraySolicitudId.add(rsResultado.getString("solicitud_id"));
                arraySolicitudCliente.add(rsResultado.getString("solicitud_cliente"));
                arraySolicitudObjetivo.add(rsResultado.getString("solicitud_objetivo"));                
                arraySolicitudDescripcion.add(rsResultado.getString("solicitud_descripcion"));  
                
                arrayEvaluacionId.add(rsResultado.getString("evaluacion_id"));
                if(rsResultado.getString("evaluacion_tipo").equals("fuerte"))
                {
                    arrayEvaluacionTipo.add("fuerte");
                }
                else
                {
                    arrayEvaluacionTipo.add("leve");
                }
                
                arrayEvaluacionEncargado.add(rsResultado.getString("evaluacion_descripcion_encargado"));
            }
            cmbSolicitud.setModel(dcbmSolicitud);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(frmCambioDerivado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluarCambio;
    private javax.swing.JCheckBox cbxEstado;
    private javax.swing.JComboBox<String> cmbSolicitud;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel pnlEquipoProyecto;
    private javax.swing.JPanel pnlEquipoProyectoCuerpo;
    private javax.swing.JPanel pnlEquipoProyectoTitlo;
    private javax.swing.JPanel pnlMetodologia;
    private javax.swing.JPanel pnlMetodologiaProyectoCuerpo;
    private javax.swing.JPanel pnlMetodologiaProyectoTitlo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalPadre;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloDatosGenerales;
    private javax.swing.JRadioButton rbnFuerte;
    private javax.swing.JRadioButton rbnLeve;
    private javax.swing.JScrollPane srpPrincipal;
    private javax.swing.JTextArea txtEvaluacionEncargado;
    private javax.swing.JTextArea txtEvaluacionJefe;
    private javax.swing.JTextField txtSolicitudCliente;
    private javax.swing.JTextArea txtSolicitudDescripcion;
    private javax.swing.JTextField txtSolicitudObjetivo;
    // End of variables declaration//GEN-END:variables
}
