/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsEvaluacionDAO;
import accesodatos.clsProyectoDAO;
import conexion.clsConexionDS;
import global.clsTablasRender;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import transferenciadatos.clsProyectoDTO;

/**
 *
 * @author Kevin
 */
public class frmCambioFinalizado extends javax.swing.JPanel {
    
    Connection conexion;
    
    /**
     * Creates new form frmProyectoArchivado
     */
    public frmCambioFinalizado() {
        initComponents();
        grupo.add(rbnAprobada);
        grupo.add(rbnDesaprobada);
        grupo.add(rbnLeve);
        grupo.add(rbnFuerte);
        
        conexion = clsConexionDS.AbrirConexion();
        CargarTablaProyectoArchivado();
        clsConexionDS.CerrarConexion(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupo = new javax.swing.ButtonGroup();
        pnlIzquierda = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlProyectos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvaluacion = new javax.swing.JTable();
        rbnLeve = new javax.swing.JRadioButton();
        rbnFuerte = new javax.swing.JRadioButton();
        rbnAprobada = new javax.swing.JRadioButton();
        rbnDesaprobada = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        pnlIzquierda.setPreferredSize(new java.awt.Dimension(500, 308));
        pnlIzquierda.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(711, 110));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(179, 229, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(671, 100));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("SOLICITUD DE CAMBIO FINALIZADA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(621, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        pnlTitulo.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTitulo.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlIzquierda.add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlProyectos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProyectos.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 200));

        tblEvaluacion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        tblEvaluacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Proyecto", "Cliente", "Objetivo Solicitud", "Descripcion Solicitud", "Tipo Cambio", "Evaluacion Encargado", "Evaluacion Comite", "Fecha Solicitud"
            }
        ));
        tblEvaluacion.setMinimumSize(new java.awt.Dimension(600, 200));
        tblEvaluacion.setPreferredSize(new java.awt.Dimension(750, 150));
        tblEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEvaluacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvaluacion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 35, 0);
        pnlProyectos.add(jScrollPane1, gridBagConstraints);

        rbnLeve.setBackground(new java.awt.Color(255, 255, 255));
        rbnLeve.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnLeve.setText("Leve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 24, 0);
        pnlProyectos.add(rbnLeve, gridBagConstraints);

        rbnFuerte.setBackground(new java.awt.Color(255, 255, 255));
        rbnFuerte.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnFuerte.setText("Fuerte");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 24);
        pnlProyectos.add(rbnFuerte, gridBagConstraints);

        rbnAprobada.setBackground(new java.awt.Color(255, 255, 255));
        rbnAprobada.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnAprobada.setSelected(true);
        rbnAprobada.setText("Aprobada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 24);
        pnlProyectos.add(rbnAprobada, gridBagConstraints);

        rbnDesaprobada.setBackground(new java.awt.Color(255, 255, 255));
        rbnDesaprobada.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        rbnDesaprobada.setText("Desaprobada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 24);
        pnlProyectos.add(rbnDesaprobada, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel3.setText("Prioridad de orden.");
        jLabel3.setMinimumSize(new java.awt.Dimension(70, 17));
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 17));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlProyectos.add(jLabel3, gridBagConstraints);

        pnlIzquierda.add(pnlProyectos, java.awt.BorderLayout.CENTER);

        add(pnlIzquierda, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblEvaluacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEvaluacionMouseClicked
        
       
        
    }//GEN-LAST:event_tblEvaluacionMouseClicked

    
    private void CargarTablaProyectoArchivado() {
        
        String[] titulos = {"id", "Proyecto", "Cliente", "Objetivo Solicitud",
                        "Descripcion Solicitud", "Tipo Cambio", "Evaluacion Encargado", 
                        "Evaluacion Comite", "Fecha Solicitud"};
        String[] fila;        
        clsEvaluacionDAO evaluacionDAO;                
        DefaultTableModel dtmEvaluacion;
        ResultSet rsResultado;
        fila = new String[10];
        dtmEvaluacion = new DefaultTableModel(null,titulos) {        
            @Override
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}               
        };        
        
        evaluacionDAO = new clsEvaluacionDAO();
        try 
        {
            rsResultado = evaluacionDAO.SeleccionarCambioFinalizado(conexion);
            while(rsResultado.next())
            {
                fila[0] = rsResultado.getString("solicitud_id");
                fila[1] = rsResultado.getString("proyecto_nombre");
                fila[2] = rsResultado.getString("solicitud_cliente");
                fila[3] = rsResultado.getString("solicitud_objetivo");
                fila[4] = rsResultado.getString("solicitud_descripcion");
                fila[5] = rsResultado.getString("evaluacion_tipo");
                fila[6] = rsResultado.getString("evaluacion_descripcion_encargado");
                fila[7] = rsResultado.getString("evaluacion_descripcion_jefe");
                fila[8] = rsResultado.getString("solicitud_fecha");
                dtmEvaluacion.addRow(fila);
            }
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(frmCambioFinalizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        tblEvaluacion.setModel(dtmEvaluacion);
        tblEvaluacion.removeColumn(tblEvaluacion.getColumnModel().getColumn(0));
        TableCellRenderer tcr =  tblEvaluacion.getTableHeader().getDefaultRenderer();
        clsTablasRender.miRender mr = new clsTablasRender.miRender(tcr);
        mr.getTableCellRendererComponent(tblEvaluacion, fila, true, true, WIDTH, 1);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlIzquierda;
    private javax.swing.JPanel pnlProyectos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JRadioButton rbnAprobada;
    private javax.swing.JRadioButton rbnDesaprobada;
    private javax.swing.JRadioButton rbnFuerte;
    private javax.swing.JRadioButton rbnLeve;
    private javax.swing.JTable tblEvaluacion;
    // End of variables declaration//GEN-END:variables
}
