/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;


import accesodatos.clsProyectoDAO;
import accesodatos.clsProyectoUsuarioDAO;
import accesodatos.clsUsuarioDAO;
import conexion.clsConexionDS;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import transferenciadatos.clsProyectoDTO;
import transferenciadatos.clsProyectoUsuarioDTO;
import transferenciadatos.clsUsuarioDTO;

/**
 * Esta clase implementa la creacion de un Nuevo Proyecto.
 * <p>
 * Esta operacion solo esta permitida a un usuario que sea Jefe de Proyecto.
 * @author Kevin
 */
public class frmEditarProyecto extends javax.swing.JPanel {
    
    Connection conexion; 
    
    DefaultListModel dlmProyectoUsuario = new DefaultListModel();
    DefaultListModel dlmUsuario = new DefaultListModel();
    ArrayList<String> arrayProyectoUsuarioId = new ArrayList();
    ArrayList<String> arrayCompararUsuarioId = new ArrayList();       
    ArrayList<String> arrayUsuarioId = new ArrayList();
    String metodologiaId;
    
    private frmPrincipal objPrincipal;
    
    //variable que maneja los usuarios existentes en el proyecto
    private int limiteUsuarioExistente = 0; 
    private int limiteUsuarioAgregado = 0;
    
    private static final Font FUENTE_DROID = new Font("Droid Sans", Font.PLAIN, 14);
    
    /**
     * Creates new form frmNuevoProyecto
     */
    public frmEditarProyecto() {
        
        initComponents();
        
        srpPrincipal.getVerticalScrollBar().setUnitIncrement(16);
        lblLiderProyecto.setText(frmPrincipal.usuarioApellidoNombre);
        
        conexion = clsConexionDS.AbrirConexion();
        ActualizarDatosProyecto();
        CargarListaProyectoUsuario();
        CargarListaUsuario();        
        clsConexionDS.CerrarConexion(conexion);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPrincipalPadre = new javax.swing.JPanel();
        srpPrincipal = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlTituloDatosGenerales = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProyectoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblLiderProyecto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProyectoDescripcion = new javax.swing.JTextArea();
        pnlEquipoProyecto = new javax.swing.JPanel();
        pnlEquipoProyectoTitlo = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlEquipoProyectoCuerpo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProyectoUsuario = new javax.swing.JList<>();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsuario = new javax.swing.JList<>();
        btnEditarProyecto = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(179, 229, 252));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("EDITAR PROYECTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        pnlTitulo.add(jPanel1, gridBagConstraints);

        add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlPrincipalPadre.setLayout(new java.awt.GridBagLayout());

        srpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        srpPrincipal.setBorder(null);

        pnlPrincipal.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnlTituloDatosGenerales.setBackground(new java.awt.Color(255, 255, 0));
        pnlTituloDatosGenerales.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlTituloDatosGenerales.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(jSeparator1, java.awt.BorderLayout.CENTER);

        pnlTituloDatosGenerales.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel4.setText("Datos generales del proyecto");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(788, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        pnlTituloDatosGenerales.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(pnlTituloDatosGenerales, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(516, 245));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 251));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        jPanel6.add(jLabel1, gridBagConstraints);

        txtProyectoNombre.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtProyectoNombre.setMinimumSize(new java.awt.Dimension(10, 30));
        txtProyectoNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 0, 0);
        jPanel6.add(txtProyectoNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Líder del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 0, 200);
        jPanel6.add(jLabel3, gridBagConstraints);

        lblLiderProyecto.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lblLiderProyecto.setText("Nombre del líder del proyecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 0, 200);
        jPanel6.add(lblLiderProyecto, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Descripción del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        jPanel6.add(jLabel6, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(264, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(264, 120));

        txtProyectoDescripcion.setColumns(20);
        txtProyectoDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtProyectoDescripcion.setRows(5);
        txtProyectoDescripcion.setMinimumSize(new java.awt.Dimension(264, 50));
        txtProyectoDescripcion.setPreferredSize(new java.awt.Dimension(264, 80));
        jScrollPane1.setViewportView(txtProyectoDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 35, 0);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(jPanel3, gridBagConstraints);

        pnlEquipoProyecto.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyecto.setLayout(new java.awt.BorderLayout());

        pnlEquipoProyectoTitlo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoTitlo.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlEquipoProyectoTitlo.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jSeparator2, java.awt.BorderLayout.CENTER);

        pnlEquipoProyectoTitlo.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel7.setText("Equipo del proyecto");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(868, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );

        pnlEquipoProyectoTitlo.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyecto.add(pnlEquipoProyectoTitlo, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyectoCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel5.setText("Equipo del proyecto.                                  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        pnlEquipoProyectoCuerpo.add(jLabel5, gridBagConstraints);

        lstProyectoUsuario.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lstProyectoUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Usuario 1", "Usuario 2", "Usuario 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProyectoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProyectoUsuarioMouseClicked(evt);
            }
        });
        lstProyectoUsuario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProyectoUsuarioValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstProyectoUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 35, 0);
        pnlEquipoProyectoCuerpo.add(jScrollPane2, gridBagConstraints);

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/left.png"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(50, 24, 5, 24);
        pnlEquipoProyectoCuerpo.add(btnIzquierda, gridBagConstraints);

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/right.png"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 50, 24);
        pnlEquipoProyectoCuerpo.add(btnDerecha, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel8.setText("Miembros disponibles.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 200);
        pnlEquipoProyectoCuerpo.add(jLabel8, gridBagConstraints);

        lstUsuario.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lstUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Usuario 4", "Usuario 5", "Usuario 6", "Usuario 7", "Usuario 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 35, 35);
        pnlEquipoProyectoCuerpo.add(jScrollPane3, gridBagConstraints);

        btnEditarProyecto.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnEditarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/content-save-all.png"))); // NOI18N
        btnEditarProyecto.setText("GUARDAR CAMBIOS");
        btnEditarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProyectoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(35, 24, 35, 100);
        pnlEquipoProyectoCuerpo.add(btnEditarProyecto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlEquipoProyectoCuerpo.add(jSeparator6, gridBagConstraints);

        pnlEquipoProyecto.add(pnlEquipoProyectoCuerpo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(pnlEquipoProyecto, gridBagConstraints);

        srpPrincipal.setViewportView(pnlPrincipal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        pnlPrincipalPadre.add(srpPrincipal, gridBagConstraints);

        add(pnlPrincipalPadre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProyectoActionPerformed
                
            clsProyectoUsuarioDAO proyectoUsuarioDAO;
            clsProyectoDAO proyectoDAO;            
            clsProyectoDTO proyectoDTO;
            clsProyectoUsuarioDTO proyectoUsuarioDTO;
            
            proyectoUsuarioDAO = new clsProyectoUsuarioDAO();
            proyectoDAO = new clsProyectoDAO();        
            proyectoDTO = new clsProyectoDTO();
            
            JLabel lblMensaje;

            conexion = clsConexionDS.AbrirConexion();

            //actualiza datos del proyecto
            proyectoDTO.setProyecto_nombre(txtProyectoNombre.getText());
            proyectoDTO.setProyecto_descripcion(txtProyectoDescripcion.getText());
            proyectoDTO.setProyecto_id(frmPrincipal.proyectoId);
            proyectoDAO.ActualizarProyecto(proyectoDTO, conexion);

            //agrega intengrantes del proyecto
            for(int i = 1; i <= limiteUsuarioAgregado; i++)
            {
                proyectoUsuarioDTO = new clsProyectoUsuarioDTO
                (
                    frmPrincipal.proyectoId,
                    arrayCompararUsuarioId.get((limiteUsuarioExistente-1)+i),
                    "",
                    "",
                    "",
                    ""
                );

                //metodo
                proyectoUsuarioDAO.CrearProyectoUsuario(proyectoUsuarioDTO, conexion);
            }

            clsConexionDS.CerrarConexion(conexion);
            
            lblMensaje = new JLabel("Se guardaron las modificaciones correctamente");
            lblMensaje.setFont(FUENTE_DROID);
            JOptionPane.showMessageDialog(this, lblMensaje, 
                    "Actualización correcta", JOptionPane.INFORMATION_MESSAGE);
            
            objPrincipal.AbrirModalProyectos();
        
    }//GEN-LAST:event_btnEditarProyectoActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
       
       if(lstUsuario.getSelectedIndex() != -1)
       {
           int auxIndex = lstUsuario.getSelectedIndex();
           
           dlmProyectoUsuario.addElement(lstUsuario.getSelectedValue());
           arrayCompararUsuarioId.add(arrayUsuarioId.get(auxIndex));
           lstProyectoUsuario.setModel(dlmProyectoUsuario);
           
           arrayUsuarioId.remove(arrayUsuarioId.get(auxIndex));
           dlmUsuario.removeElement(lstUsuario.getSelectedValue());
           lstUsuario.setModel(dlmUsuario);       
           
           limiteUsuarioAgregado++;
       }
                
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed

        if(lstProyectoUsuario.getSelectedIndex() != -1)
        {
            int auxIndex = lstProyectoUsuario.getSelectedIndex();

            dlmUsuario.addElement(lstProyectoUsuario.getSelectedValue());
            arrayUsuarioId.add(arrayCompararUsuarioId.get(auxIndex));
            lstUsuario.setModel(dlmUsuario);

            arrayCompararUsuarioId.remove(arrayCompararUsuarioId.get(auxIndex));
            dlmProyectoUsuario.removeElement(lstProyectoUsuario.getSelectedValue());
            lstProyectoUsuario.setModel(dlmProyectoUsuario);
            limiteUsuarioAgregado--;
        }

    }//GEN-LAST:event_btnDerechaActionPerformed

    private void lstProyectoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProyectoUsuarioMouseClicked
        
        if(lstProyectoUsuario.getSelectedIndex() < limiteUsuarioExistente)
        {
            lstProyectoUsuario.clearSelection();
        }
        
    }//GEN-LAST:event_lstProyectoUsuarioMouseClicked

    private void lstProyectoUsuarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProyectoUsuarioValueChanged
        
        if(lstProyectoUsuario.getSelectedIndex() != -1)
        {
            if(lstProyectoUsuario.getSelectedIndex() < limiteUsuarioExistente)
            {
                lstProyectoUsuario.clearSelection();
            }
        }        
        
    }//GEN-LAST:event_lstProyectoUsuarioValueChanged

    /**
     * Obtiene el objeto frmPrincipal.
     * Permite usar las funciones de frmPrincipal.
     * @param xFormulario objeto frmPrincipal.
     */
    public void FormularioPrincipal(frmPrincipal xFormulario) {
       
        this.objPrincipal = xFormulario;
        
    }
    
    private void CargarListaUsuario() {
        
        clsUsuarioDAO usuarioDAO = new clsUsuarioDAO();
        ArrayList<clsUsuarioDTO> arrayUsuario;
        String fila[];                
        dlmUsuario.removeAllElements();
        fila = new String [3];       
        arrayUsuario = usuarioDAO.SeleccionarUsuario(conexion);
        for(clsUsuarioDTO u : arrayUsuario) 
        {
            fila[0] = u.getUsuario_apellido() + ", " + u.getUsuario_nombre();
            fila[1] = u.getUsuario_id();
            fila[2] = u.getUsuario_jefe_proyecto();            
            if( !arrayCompararUsuarioId.contains(fila[1]) )
            {                
                dlmUsuario.addElement(fila[0]);
                arrayUsuarioId.add(fila[1]);                
            }
        }
        lstUsuario.setModel(dlmUsuario);
        
    }
    
    private void ActualizarDatosProyecto() {
        
        ResultSet rsResultado;
        clsProyectoDAO proyectoDAO = new clsProyectoDAO();
        
        try 
        {
            rsResultado = proyectoDAO.SeleccionarProyecto(frmPrincipal.proyectoId, conexion);
            while(rsResultado.next())
            {
                txtProyectoNombre.setText(rsResultado.getString("proyecto_nombre"));
                txtProyectoDescripcion.setText(rsResultado.getString("proyecto_descripcion"));
            }
        }
        catch (SQLException ex) 
        {
            
            Logger.getLogger(frmEditarProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void CargarListaProyectoUsuario() {
        
        ResultSet rsResultado;
        clsProyectoUsuarioDAO proyectoUsuarioDAO = new clsProyectoUsuarioDAO();
        dlmProyectoUsuario.removeAllElements();
        limiteUsuarioExistente = 0;
        try 
        {
            rsResultado = proyectoUsuarioDAO.SeleccionarProyectoEquipo(frmPrincipal.proyectoId, conexion);
            while(rsResultado.next())
            {
                dlmProyectoUsuario.addElement(rsResultado.getString("usuario_apellido")+", "+rsResultado.getString("usuario_nombre"));
                arrayProyectoUsuarioId.add(rsResultado.getString("proyectousuario_id"));
                arrayCompararUsuarioId.add(rsResultado.getString("usuario_id"));
                limiteUsuarioExistente++;
            }
            lstProyectoUsuario.setModel(dlmProyectoUsuario);
        }
        catch (Exception ex) 
        {
            Logger.getLogger(frmEditarProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnEditarProyecto;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblLiderProyecto;
    private javax.swing.JList<String> lstProyectoUsuario;
    private javax.swing.JList<String> lstUsuario;
    private javax.swing.JPanel pnlEquipoProyecto;
    private javax.swing.JPanel pnlEquipoProyectoCuerpo;
    private javax.swing.JPanel pnlEquipoProyectoTitlo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalPadre;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloDatosGenerales;
    private javax.swing.JScrollPane srpPrincipal;
    private javax.swing.JTextArea txtProyectoDescripcion;
    private javax.swing.JTextField txtProyectoNombre;
    // End of variables declaration//GEN-END:variables
}
