/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsEntregableRevisionDAO;
import accesodatos.clsEntregableVersionDAO;
import conexion.clsConexionDS;
import global.clsTablasRender.miRender;
import java.awt.Dimension;
import java.awt.Window;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import transferenciadatos.clsEntregableRevisionDTO;
import transferenciadatos.clsEntregableVersionDTO;



/**
 *
 * @author Kevin
 */
public class frmGenerarVersion extends javax.swing.JDialog {

    String proyectoId;
    Connection conexion;
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
     ArrayList<String> arrayRevisionId = new ArrayList();
     ArrayList<String> arrayRevisionEnlace = new ArrayList();
     ArrayList<String> arrayVersionId = new ArrayList();
    /**
     * Creates new form frmArchivarProyecto
     * @param parentWindow
     */
    public frmGenerarVersion(Window parentWindow) {
        super(parentWindow);
        initComponents();
        this.setLocationRelativeTo(parentWindow);
        txtFechaVersion.setDateFormat(dateFormat);    
        spnCuerpo.getVerticalScrollBar().setUnitIncrement(16);
        this.setPreferredSize(new Dimension(1025, 721));
        
        conexion = clsConexionDS.AbrirConexion();  
        CargarComboRevision();
        CargarTablaVersionComboPredecesor();
        CargarEnlaceRevision();
        clsConexionDS.CerrarConexion(conexion);
        
        System.out.println("entregable: "+frmAdministrarProyecto.entregableSeleccionadoId);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlRevisionTitulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlCuerpo = new javax.swing.JPanel();
        pnlRevisionSubtitulo = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        spnCuerpo = new javax.swing.JScrollPane();
        pnlRevisionCuerpo1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreVersion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivoVersion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbPredecesor = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtEnlaceRevision = new javax.swing.JTextField();
        txtFechaVersion = new com.alee.extended.date.WebDateField();
        jLabel13 = new javax.swing.JLabel();
        txtEnlaceVersion = new javax.swing.JTextField();
        btnAbrirEnlace = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVersion = new javax.swing.JTable();
        btnGenerarVersion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbRevision = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Archivar Proyecto");
        setPreferredSize(new java.awt.Dimension(1025, 721));

        pnlRevisionTitulo.setBackground(new java.awt.Color(178, 223, 219));
        pnlRevisionTitulo.setMinimumSize(new java.awt.Dimension(650, 100));
        pnlRevisionTitulo.setPreferredSize(new java.awt.Dimension(650, 100));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel4.setText("GENERAR VERSION");

        javax.swing.GroupLayout pnlRevisionTituloLayout = new javax.swing.GroupLayout(pnlRevisionTitulo);
        pnlRevisionTitulo.setLayout(pnlRevisionTituloLayout);
        pnlRevisionTituloLayout.setHorizontalGroup(
            pnlRevisionTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRevisionTituloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(790, Short.MAX_VALUE))
        );
        pnlRevisionTituloLayout.setVerticalGroup(
            pnlRevisionTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRevisionTituloLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnlRevisionTitulo, java.awt.BorderLayout.PAGE_START);

        pnlCuerpo.setLayout(new java.awt.BorderLayout());

        pnlRevisionSubtitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlRevisionSubtitulo.setMinimumSize(new java.awt.Dimension(650, 110));
        pnlRevisionSubtitulo.setPreferredSize(new java.awt.Dimension(650, 110));
        pnlRevisionSubtitulo.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(0, 10));
        jPanel13.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel13.setLayout(new java.awt.BorderLayout());
        jPanel13.add(jSeparator4, java.awt.BorderLayout.CENTER);

        pnlRevisionSubtitulo.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMinimumSize(new java.awt.Dimension(0, 100));

        jLabel14.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel14.setText("Datos de la versión");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(20, 20, 20))
        );

        pnlRevisionSubtitulo.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        pnlCuerpo.add(pnlRevisionSubtitulo, java.awt.BorderLayout.PAGE_START);

        spnCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        spnCuerpo.setBorder(null);
        spnCuerpo.setPreferredSize(new java.awt.Dimension(800, 700));

        pnlRevisionCuerpo1.setBackground(new java.awt.Color(255, 255, 255));
        pnlRevisionCuerpo1.setMinimumSize(new java.awt.Dimension(692, 100));
        pnlRevisionCuerpo1.setPreferredSize(new java.awt.Dimension(790, 800));
        pnlRevisionCuerpo1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de la versión.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlRevisionCuerpo1.add(jLabel2, gridBagConstraints);

        txtNombreVersion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtNombreVersion.setMinimumSize(new java.awt.Dimension(10, 30));
        txtNombreVersion.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlRevisionCuerpo1.add(txtNombreVersion, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de la versión.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 10, 0);
        pnlRevisionCuerpo1.add(jLabel5, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(264, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(264, 120));

        txtMotivoVersion.setColumns(20);
        txtMotivoVersion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtMotivoVersion.setRows(5);
        txtMotivoVersion.setMinimumSize(new java.awt.Dimension(264, 50));
        txtMotivoVersion.setPreferredSize(new java.awt.Dimension(264, 80));
        jScrollPane2.setViewportView(txtMotivoVersion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlRevisionCuerpo1.add(jScrollPane2, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel10.setText("Motivo de la versión.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        pnlRevisionCuerpo1.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel11.setText("Predecesor.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlRevisionCuerpo1.add(jLabel11, gridBagConstraints);

        cmbPredecesor.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        cmbPredecesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlRevisionCuerpo1.add(cmbPredecesor, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel12.setText("Enlace de la revisión.                        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 10, 24);
        pnlRevisionCuerpo1.add(jLabel12, gridBagConstraints);

        txtEnlaceRevision.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtEnlaceRevision.setForeground(new java.awt.Color(0, 0, 255));
        txtEnlaceRevision.setDisabledTextColor(new java.awt.Color(0, 0, 255));
        txtEnlaceRevision.setEnabled(false);
        txtEnlaceRevision.setMinimumSize(new java.awt.Dimension(10, 30));
        txtEnlaceRevision.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 24);
        pnlRevisionCuerpo1.add(txtEnlaceRevision, gridBagConstraints);

        txtFechaVersion.setText("Seleccione una fecha");
        txtFechaVersion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 24);
        pnlRevisionCuerpo1.add(txtFechaVersion, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel13.setText("Enlace de la versión.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlRevisionCuerpo1.add(jLabel13, gridBagConstraints);

        txtEnlaceVersion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtEnlaceVersion.setForeground(new java.awt.Color(0, 0, 255));
        txtEnlaceVersion.setMinimumSize(new java.awt.Dimension(10, 30));
        txtEnlaceVersion.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlRevisionCuerpo1.add(txtEnlaceVersion, gridBagConstraints);

        btnAbrirEnlace.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        btnAbrirEnlace.setText("Abrir Enlace");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 35);
        pnlRevisionCuerpo1.add(btnAbrirEnlace, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel15.setText("Versiones del entregable.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlRevisionCuerpo1.add(jLabel15, gridBagConstraints);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(650, 150));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(650, 150));

        tblVersion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        tblVersion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblVersion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 35, 24);
        pnlRevisionCuerpo1.add(jScrollPane3, gridBagConstraints);

        btnGenerarVersion.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnGenerarVersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/settings.png"))); // NOI18N
        btnGenerarVersion.setText("GENERAR VERSION");
        btnGenerarVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVersionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(35, 0, 24, 35);
        pnlRevisionCuerpo1.add(btnGenerarVersion, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlRevisionCuerpo1.add(jSeparator1, gridBagConstraints);

        cmbRevision.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        cmbRevision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRevision.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRevisionItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlRevisionCuerpo1.add(cmbRevision, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel16.setText("Versión originada por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlRevisionCuerpo1.add(jLabel16, gridBagConstraints);

        spnCuerpo.setViewportView(pnlRevisionCuerpo1);

        pnlCuerpo.add(spnCuerpo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCuerpo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVersionActionPerformed
       
        String fecha;
        clsEntregableVersionDAO entregableVersionDAO;
        clsEntregableVersionDTO entregableVersionDTO;
        
        fecha = dateFormat.format(txtFechaVersion.getDate());
        entregableVersionDAO = new clsEntregableVersionDAO();
        if(arrayVersionId.isEmpty() == false){
            entregableVersionDTO = new clsEntregableVersionDTO (
                            "",
                            txtNombreVersion.getText(),
                            fecha,
                            txtEnlaceVersion.getText(),
                            txtMotivoVersion.getText(),
                            arrayRevisionId.get(cmbRevision.getSelectedIndex()),
                            "",
                            arrayVersionId.get(cmbPredecesor.getSelectedIndex()),
                            ""
                        );
        }
        else
        {
            entregableVersionDTO = new clsEntregableVersionDTO (
                            "",
                            txtNombreVersion.getText(),
                            fecha,
                            txtEnlaceVersion.getText(),
                            txtMotivoVersion.getText(),
                            arrayRevisionId.get(cmbRevision.getSelectedIndex()),
                            "",
                            "1",
                            ""
                        );
        }
        
        conexion = clsConexionDS.AbrirConexion();
        entregableVersionDAO.CrearEntregableVersion(entregableVersionDTO, conexion);
        CargarTablaVersionComboPredecesor();
        clsConexionDS.CerrarConexion(conexion);
    }//GEN-LAST:event_btnGenerarVersionActionPerformed

    private void cmbRevisionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRevisionItemStateChanged
       
        if(cmbRevision.getSelectedIndex() != -1)
        {
            CargarEnlaceRevision();
        }
        
    }//GEN-LAST:event_cmbRevisionItemStateChanged

    private void CargarEnlaceRevision() {
               
        txtEnlaceRevision.setText (
                arrayRevisionEnlace.get(cmbRevision.getSelectedIndex())
            );
        
    }
    
    private void CargarComboRevision() {
        
        
        String[] fila;
        clsEntregableRevisionDAO entregableRevisionDAO;
        ArrayList<clsEntregableRevisionDTO> arrayEntregableRevision;   
        DefaultComboBoxModel dcbmPredecesor;        
        fila = new String [8];
        arrayRevisionId.clear(); 
        arrayRevisionEnlace.clear();
        dcbmPredecesor = new DefaultComboBoxModel();
        entregableRevisionDAO = new clsEntregableRevisionDAO();
        arrayEntregableRevision = entregableRevisionDAO.SeleccionarEntregableRevision (
                            frmAdministrarProyecto.entregableSeleccionadoId,
                            conexion
                        );
        dcbmPredecesor.removeAllElements();
        for(clsEntregableRevisionDTO er : arrayEntregableRevision)
        {
            fila[0] = er.getRevision_id();
            fila[1] = er.getEntregable_id();
            fila[2] = er.getRevision_id_hijo();
            fila[3] = er.getRevision_nombre();  
            fila[4] = er.getRevision_enlace();
            dcbmPredecesor.addElement(fila[3]);
            arrayRevisionId.add(fila[0]);
            arrayRevisionEnlace.add(fila[4]);
        }         
        cmbRevision.setModel(dcbmPredecesor);
    }
    
    private void CargarTablaVersionComboPredecesor() {
        
        String[] titulos = {"version id", "revision id", "version id hijo",
                            "Version", "Fecha", "Motivo", "Enlace", "Originado por","Predecesor"};
        String[] fila;
        clsEntregableVersionDAO entregableVersionDAO;
        ArrayList<clsEntregableVersionDTO> arrayEntregableVersion;
        DefaultTableModel dtmVersion;
        DefaultComboBoxModel dcbmPredecesor;
        
        fila = new String [9];
        arrayVersionId.clear();
        dtmVersion = new DefaultTableModel(null,titulos) {        
            @Override
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}               
        };
        dcbmPredecesor = new DefaultComboBoxModel();
        entregableVersionDAO = new clsEntregableVersionDAO();
        arrayEntregableVersion = entregableVersionDAO.SeleccionarEntregableVersion (
                            frmAdministrarProyecto.entregableSeleccionadoId,
                            conexion
                        );
        dcbmPredecesor.removeAllElements();
        for(clsEntregableVersionDTO ev : arrayEntregableVersion)
        {
            fila[0] = ev.getVersion_id();
            fila[1] = ev.getRevision_id();
            fila[2] = ev.getVersion_id_hijo();
            fila[3] = ev.getVersion_nombre();
            fila[4] = ev.getVersion_fecha();
            fila[5] = ev.getVersion_descripcion();
            fila[6] = ev.getVersion_enlace();
            fila[7] = ev.getRevision_nombre();
            fila[8] = ev.getVersion_nombre_hijo();
            dtmVersion.addRow(fila);
            dcbmPredecesor.addElement(fila[3]);
            arrayVersionId.add(fila[0]);
        }
        
        tblVersion.setModel(dtmVersion);
        tblVersion.removeColumn(tblVersion.getColumnModel().getColumn(0));
        tblVersion.removeColumn(tblVersion.getColumnModel().getColumn(0));
        tblVersion.removeColumn(tblVersion.getColumnModel().getColumn(0));
        TableCellRenderer tcr =  tblVersion.getTableHeader().getDefaultRenderer();
        miRender mr = new miRender(tcr);
        mr.getTableCellRendererComponent(tblVersion, fila, true, true, WIDTH, 0);
        mr.getTableCellRendererComponent(tblVersion, fila, true, true, WIDTH, 1);
        
        cmbPredecesor.setModel(dcbmPredecesor);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirEnlace;
    private javax.swing.JButton btnGenerarVersion;
    private javax.swing.JComboBox<String> cmbPredecesor;
    private javax.swing.JComboBox<String> cmbRevision;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pnlCuerpo;
    private javax.swing.JPanel pnlRevisionCuerpo1;
    private javax.swing.JPanel pnlRevisionSubtitulo;
    private javax.swing.JPanel pnlRevisionTitulo;
    private javax.swing.JScrollPane spnCuerpo;
    private javax.swing.JTable tblVersion;
    private javax.swing.JTextField txtEnlaceRevision;
    private javax.swing.JTextField txtEnlaceVersion;
    private com.alee.extended.date.WebDateField txtFechaVersion;
    private javax.swing.JTextArea txtMotivoVersion;
    private javax.swing.JTextField txtNombreVersion;
    // End of variables declaration//GEN-END:variables
}
