/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsUsuarioDAO;
import conexion.clsConexionDS;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Formulario de Inicio de Sesion del Sistema.
 * @author      Kevin Montes De Oca V.
 * @version     %I%, %G%
 */
public class frmInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form frmInicioSesion
     */
    private String usuarioNombre;
    private String usuarioApellido;
    private String usuarioJefeProyecto;
    private String usuarioId;
    Connection conexion;
    
    public frmInicioSesion() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(515, 274));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(711, 110));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(179, 229, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(671, 100));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        pnlTitulo.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTitulo.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        txtCodigo.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtCodigo.setText("2008032376");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 0, 0);
        jPanel3.add(txtCodigo, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        txtContrasena.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtContrasena.setText("123");
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 0, 0);
        jPanel3.add(txtContrasena, gridBagConstraints);

        btnIngresar.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/account-key.png"))); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 35, 24);
        jPanel3.add(btnIngresar, gridBagConstraints);

        btnCancelar.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/cancel.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 35, 0);
        jPanel3.add(btnCancelar, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        //declaracion de variables
        String codigo;
        String contrasena;
        
        //toma de datos
        codigo = txtCodigo.getText();
        char[] aux = txtContrasena.getPassword();
        contrasena = new String(aux);
        
        try 
        {
            //Comprueba el usuario y la contraseña
            if(ComprobarUsuarioContrasena(codigo,contrasena))
            {
                JOptionPane.showMessageDialog(this, "Bienvenido(a):\n"+
                        usuarioApellido+", "+usuarioNombre,
                        "Acceso correcto =)",JOptionPane.INFORMATION_MESSAGE);
                         
                if(usuarioJefeProyecto.equals("1"))
                {
                    AbrirVentanaPrincipal(true, usuarioApellido+", "+usuarioNombre, usuarioId);
                }
                else
                {
                    AbrirVentanaPrincipal(false, usuarioApellido+", "+usuarioNombre, usuarioId);
                }                
                this.dispose();                
            }
        } catch (Exception ex) {
            Logger.getLogger(frmInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            btnIngresarActionPerformed(null);
        }
        
    }//GEN-LAST:event_txtContrasenaKeyPressed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            btnIngresarActionPerformed(null);
        }
        
    }//GEN-LAST:event_txtCodigoKeyPressed

    /**
     * Permite comprobar el codigo y contraseña del usuario que iniciara sesion.
     * @param xCodigo   el codigo ingresado por el usuario.
     * @param xContrasena la contraseña ingresada por el usuario.
     * @return usuarioContrasenaCorrecto true si se comprueban los datos.
     * @throws Exception Excepcion en el ResultSet rsDatos.
     */
    private boolean ComprobarUsuarioContrasena(String xCodigo, String xContrasena) throws Exception {
                
        ResultSet rsDatos;
        clsUsuarioDAO usuarioDAO = new clsUsuarioDAO();        
        conexion = clsConexionDS.AbrirConexion();
        boolean usuarioContrasenaCorrecto = false;
        
        try
        {
            rsDatos = usuarioDAO.SeleccionarUsuarioCodigo(xCodigo, conexion);            
            while(rsDatos.next())
            {
                if(xContrasena.equals(rsDatos.getString("usuario_contrasena")))
                {
                   usuarioContrasenaCorrecto = true;
                   usuarioNombre = rsDatos.getString("usuario_nombre");
                   usuarioApellido = rsDatos.getString("usuario_apellido");
                   usuarioJefeProyecto = rsDatos.getString("usuario_jefe_proyecto");
                   usuarioId = rsDatos.getString("usuario_id");
                }
                else
                {
                    usuarioContrasenaCorrecto = false;
                    JOptionPane.showMessageDialog(this, "Contraseña Incorrecta", 
                                        "Error autenticando", 0);
                }
            }
            clsConexionDS.CerrarConexion(conexion);
        }
        catch(Exception ex)
        {
            throw ex;
        }
        return usuarioContrasenaCorrecto;
    }
    
    /**
     * Abre el formulario Principal {@link frmPrincipal} donde se trabajara
     * con las ventanas modales del sistema.
     * <p>
     * Se visualiza el formulario, se centra y se maximiza.
     * @param xJefeProyecto variable que ira al formulario Principal {@link frmPrincipal}
     * @param xUsuario variable que ira al formulario Principal {@link frmPrincipal}
     * para que todo el sistema identifique si el usuario es jefe de proyecto o no.
     */
    private void AbrirVentanaPrincipal 
        (
            boolean xJefeProyecto,
            String xUsuario, 
            String xUsuarioId
        ) {
        
        vistacontrol.frmPrincipal obj= new vistacontrol.frmPrincipal(
                xJefeProyecto, xUsuario, xUsuarioId
                );  
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);        
        
    }
    
     
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
