/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsMetodologiaDAO;
import accesodatos.clsProyectoDAO;
import accesodatos.clsProyectoEntregableDAO;
import accesodatos.clsProyectoUsuarioDAO;
import accesodatos.clsUsuarioDAO;
import conexion.clsConexionDS;
import global.clsFechas;
import global.clsFuncionesBD;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import transferenciadatos.clsMetodologiaDTO;
import transferenciadatos.clsProyectoDTO;
import transferenciadatos.clsProyectoEntregableDTO;
import transferenciadatos.clsProyectoUsuarioDTO;
import transferenciadatos.clsUsuarioDTO;

/**
 * Esta clase implementa la creacion de un Nuevo Proyecto.
 * <p>
 * Esta operacion solo esta permitida a un usuario que sea Jefe de Proyecto.
 * @author Kevin
 */
public class frmNuevoProyecto extends javax.swing.JPanel {
    
    //declaracion listas
    DefaultListModel dlmUsuario = new DefaultListModel();
    DefaultListModel dlmProyectoUsuario = new DefaultListModel();
    //declaracion arrays
    ArrayList<String> arrayUsuarioId = new ArrayList();
    ArrayList<String> arrayProyectoUsuarioId = new ArrayList();
    ArrayList<String> arrayMetodologiaId = new ArrayList();
    ArrayList<String> arrayMetodologiaDescripcion = new ArrayList();    
    //declaracion nodos
    DefaultMutableTreeNode dmtnMetodologia;
    DefaultMutableTreeNode dmtnEtapa;
    DefaultMutableTreeNode dmtnEntregable;    
    //variable para el formulario principal
    private frmPrincipal objPrincipal;
    
    private final String GOOGLE_DOCS_DEFAULT_URL = "https://docs.google.com/?hl=es";
    private static final Font FUENTE_DROID = new Font("Droid Sans", Font.PLAIN, 14);
    
    /**
     * Creates new form frmNuevoProyecto
     */
    public frmNuevoProyecto() {
        
        initComponents();
        
        srpPrincipal.getVerticalScrollBar().setUnitIncrement(16);
        CargarListaProyectoUsuario();
        CargarListaUsuario();
        CargarListaMetodologia();
        lblLiderProyecto.setText(frmPrincipal.usuarioApellidoNombre);        
        lstMetodologia.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitulo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlPrincipalPadre = new javax.swing.JPanel();
        srpPrincipal = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlTituloDatosGenerales = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProyectoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblLiderProyecto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProyectoDescripcion = new javax.swing.JTextArea();
        pnlEquipoProyecto = new javax.swing.JPanel();
        pnlEquipoProyectoTitlo = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlEquipoProyectoCuerpo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProyectoUsuario = new javax.swing.JList<>();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstUsuario = new javax.swing.JList<>();
        pnlMetodologia = new javax.swing.JPanel();
        pnlMetodologiaProyectoTitlo = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlMetodologiaProyectoCuerpo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstMetodologia = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMetodologiaDescripcion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        treEntregable = new com.alee.extended.tree.WebCheckBoxTree();
        btnCrearProyecto = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(179, 229, 252));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("NUEVO PROYECTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        pnlTitulo.add(jPanel1, gridBagConstraints);

        add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlPrincipalPadre.setLayout(new java.awt.GridBagLayout());

        srpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        srpPrincipal.setBorder(null);

        pnlPrincipal.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        pnlTituloDatosGenerales.setBackground(new java.awt.Color(255, 255, 0));
        pnlTituloDatosGenerales.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlTituloDatosGenerales.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(jSeparator1, java.awt.BorderLayout.CENTER);

        pnlTituloDatosGenerales.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel4.setText("Datos generales del proyecto");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(758, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        pnlTituloDatosGenerales.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(pnlTituloDatosGenerales, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(516, 245));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 251));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        jPanel6.add(jLabel1, gridBagConstraints);

        txtProyectoNombre.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtProyectoNombre.setMinimumSize(new java.awt.Dimension(10, 30));
        txtProyectoNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 0, 0);
        jPanel6.add(txtProyectoNombre, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setText("Líder del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 0, 200);
        jPanel6.add(jLabel3, gridBagConstraints);

        lblLiderProyecto.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lblLiderProyecto.setText("Nombre del líder del proyecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 0, 200);
        jPanel6.add(lblLiderProyecto, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel6.setText("Descripción del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        jPanel6.add(jLabel6, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(264, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(264, 120));

        txtProyectoDescripcion.setColumns(20);
        txtProyectoDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtProyectoDescripcion.setRows(5);
        txtProyectoDescripcion.setMinimumSize(new java.awt.Dimension(264, 50));
        txtProyectoDescripcion.setPreferredSize(new java.awt.Dimension(264, 80));
        jScrollPane1.setViewportView(txtProyectoDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 35, 0);
        jPanel6.add(jScrollPane1, gridBagConstraints);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(jPanel3, gridBagConstraints);

        pnlEquipoProyecto.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyecto.setLayout(new java.awt.BorderLayout());

        pnlEquipoProyectoTitlo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoTitlo.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlEquipoProyectoTitlo.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jSeparator2, java.awt.BorderLayout.CENTER);

        pnlEquipoProyectoTitlo.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel7.setText("Equipo del proyecto");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(838, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );

        pnlEquipoProyectoTitlo.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyecto.add(pnlEquipoProyectoTitlo, java.awt.BorderLayout.PAGE_START);

        pnlEquipoProyectoCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEquipoProyectoCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel5.setText("Equipo del proyecto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 0, 0);
        pnlEquipoProyectoCuerpo.add(jLabel5, gridBagConstraints);

        lstProyectoUsuario.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lstProyectoUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Usuario 1", "Usuario 2", "Usuario 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstProyectoUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 35, 35, 0);
        pnlEquipoProyectoCuerpo.add(jScrollPane2, gridBagConstraints);

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/left.png"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(50, 24, 5, 24);
        pnlEquipoProyectoCuerpo.add(btnIzquierda, gridBagConstraints);

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/right.png"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 24, 50, 24);
        pnlEquipoProyectoCuerpo.add(btnDerecha, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel8.setText("Miembros disponibles.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 200);
        pnlEquipoProyectoCuerpo.add(jLabel8, gridBagConstraints);

        lstUsuario.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lstUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Usuario 4", "Usuario 5", "Usuario 6", "Usuario 7", "Usuario 8" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstUsuario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 35, 200);
        pnlEquipoProyectoCuerpo.add(jScrollPane3, gridBagConstraints);

        pnlEquipoProyecto.add(pnlEquipoProyectoCuerpo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        pnlPrincipal.add(pnlEquipoProyecto, gridBagConstraints);

        pnlMetodologia.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologia.setLayout(new java.awt.BorderLayout());

        pnlMetodologiaProyectoTitlo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologiaProyectoTitlo.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlMetodologiaProyectoTitlo.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(jSeparator3, java.awt.BorderLayout.CENTER);

        pnlMetodologiaProyectoTitlo.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel10.setText("Metodología");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(902, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(20, 20, 20))
        );

        pnlMetodologiaProyectoTitlo.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        pnlMetodologia.add(pnlMetodologiaProyectoTitlo, java.awt.BorderLayout.PAGE_START);

        pnlMetodologiaProyectoCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMetodologiaProyectoCuerpo.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel11.setText("Plantillas disponibles.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlMetodologiaProyectoCuerpo.add(jLabel11, gridBagConstraints);

        lstMetodologia.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        lstMetodologia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Motodologia 1", "Motodologia 2", "Motodologia 3", "Motodologia 4", "Motodologia 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstMetodologia.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMetodologiaValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstMetodologia);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        pnlMetodologiaProyectoCuerpo.add(jScrollPane4, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel12.setText("Descripción.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(24, 24, 10, 200);
        pnlMetodologiaProyectoCuerpo.add(jLabel12, gridBagConstraints);

        txtMetodologiaDescripcion.setColumns(20);
        txtMetodologiaDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtMetodologiaDescripcion.setLineWrap(true);
        txtMetodologiaDescripcion.setRows(5);
        txtMetodologiaDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMetodologiaDescripcion.setEnabled(false);
        jScrollPane5.setViewportView(txtMetodologiaDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 0, 400);
        pnlMetodologiaProyectoCuerpo.add(jScrollPane5, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel13.setText("Seleccione entregables.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 35, 10, 0);
        pnlMetodologiaProyectoCuerpo.add(jLabel13, gridBagConstraints);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Metodologia");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Fase1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("actividad1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("actividad2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("actividad3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("actividad4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treEntregable.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treEntregable.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(treEntregable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 35, 0);
        pnlMetodologiaProyectoCuerpo.add(jScrollPane6, gridBagConstraints);

        btnCrearProyecto.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnCrearProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/content-save-all.png"))); // NOI18N
        btnCrearProyecto.setText("CREAR PROYECTO");
        btnCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProyectoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(35, 24, 35, 100);
        pnlMetodologiaProyectoCuerpo.add(btnCrearProyecto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlMetodologiaProyectoCuerpo.add(jSeparator6, gridBagConstraints);

        pnlMetodologia.add(pnlMetodologiaProyectoCuerpo, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlPrincipal.add(pnlMetodologia, gridBagConstraints);

        srpPrincipal.setViewportView(pnlPrincipal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        pnlPrincipalPadre.add(srpPrincipal, gridBagConstraints);

        add(pnlPrincipalPadre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lstMetodologiaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMetodologiaValueChanged
        
        String auxMetodologiaNombre;
        //cada vez que se selecciona una metodologia, el arbol se actualiza y
        //la drescripcion tambien.
        if(lstMetodologia.getSelectedIndex() != -1)
        {
            txtMetodologiaDescripcion.setText(arrayMetodologiaDescripcion.get(
                    lstMetodologia.getSelectedIndex()));
            
            auxMetodologiaNombre = lstMetodologia.getSelectedValue();
            dmtnMetodologia = new DefaultMutableTreeNode(auxMetodologiaNombre);
            CargarArbolMetodologia();
        }
        
    }//GEN-LAST:event_lstMetodologiaValueChanged

    private void btnCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProyectoActionPerformed
        
        //Declaraciones
        String proyectoCreadoId = "";
        String fechaActual = clsFechas.ObtenerFechaActual();        
        String entregableId;
        
        clsProyectoDTO proyectoDTO = new clsProyectoDTO();
        clsProyectoDAO proyectoDAO = new clsProyectoDAO();
        clsProyectoUsuarioDTO proyectoUsuarioDTO;
        clsProyectoUsuarioDAO proyectoUsuarioDAO = new clsProyectoUsuarioDAO();
        clsProyectoEntregableDTO proyectoEntregableDTO;
        clsProyectoEntregableDAO proyectoEntregableDAO = new clsProyectoEntregableDAO();
        Connection conexion;
        
        JLabel lblMensaje;
        
        try
        {
            conexion = clsConexionDS.AbrirConexion();
            //INSERT PROYECTO            
            proyectoDTO.setProyecto_nombre(txtProyectoNombre.getText());
            proyectoDTO.setProyecto_descripcion(txtProyectoDescripcion.getText());
            proyectoDTO.setProyecto_fecha_creacion(clsFechas.ObtenerFechaActual());

            //metodo
            proyectoDAO.CrearProyecto(proyectoDTO, conexion);

            //OBTENER ID DEL PROYECTO QUE SE CREO
            try 
            {
                proyectoCreadoId = clsFuncionesBD.ObtenerUltimoIdInsertado(conexion);
            } 
            catch (Exception ex) 
            {
                Logger.getLogger(frmNuevoProyecto.class.getName()).log(Level.SEVERE, null, ex);
            }

            //INSERT EQUIPO PROYECTO
            for(String id : arrayProyectoUsuarioId)
            {
                proyectoUsuarioDTO = new clsProyectoUsuarioDTO
                (
                    proyectoCreadoId,
                    id,
                    "",
                    "",
                    "",
                    ""
                );

                //metodo
                proyectoUsuarioDAO.CrearProyectoUsuario(proyectoUsuarioDTO, conexion);

            }

            //INSERT ENTREGABLES
            java.util.List paths = treEntregable.getCheckedNodes(false);
            for (Iterator it = paths.iterator(); it.hasNext();) 
            {
                String[] auxPartes = it.next().toString().split("-");
                entregableId = auxPartes[0].trim();
                
                if(auxPartes.length > 1)
                {
                    proyectoEntregableDTO = new clsProyectoEntregableDTO (
                                            "",
                                            proyectoCreadoId,
                                            entregableId,
                                            fechaActual,
                                            GOOGLE_DOCS_DEFAULT_URL    
                                        );

                    //metodo
                    proyectoEntregableDAO.CrearProyectoEntregable(proyectoEntregableDTO, conexion);
                    //System.out.println("Checked: "+ it.next());   
                }                         
            }  
            clsConexionDS.CerrarConexion(conexion);
            
            lblMensaje = new JLabel("Se creó el proyecto correctamente");
            lblMensaje.setFont(FUENTE_DROID);
            JOptionPane.showMessageDialog(this, lblMensaje, 
                    "Creación correcta", JOptionPane.INFORMATION_MESSAGE);
            objPrincipal.AbrirModalProyectos();
        }
        catch (HeadlessException ex)
        {
            
            Logger.getLogger(frmNuevoProyecto.class.getName()).log(Level.SEVERE, null, ex);
                            
        }
        
        
    }//GEN-LAST:event_btnCrearProyectoActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
       
        if(lstUsuario.getSelectedIndex() != -1)
        {
            int auxIndex = lstUsuario.getSelectedIndex();
        
            //pasar elementos a equipo (lstProyectoUsuario)
            dlmProyectoUsuario.addElement(lstUsuario.getSelectedValue());
            arrayProyectoUsuarioId.add(arrayUsuarioId.get(auxIndex));
            lstProyectoUsuario.setModel(dlmProyectoUsuario);
            System.out.println("<- Agregado: "+ arrayUsuarioId.get(auxIndex) +" - "+ lstUsuario.getSelectedValue());
            
            //quitar elementos de miembros disponibles (lstUsuario)    
            arrayUsuarioId.remove(arrayUsuarioId.get(auxIndex));
            dlmUsuario.removeElement(lstUsuario.getSelectedValue());            
            lstUsuario.setModel(dlmUsuario);            
        }
                
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        
        if(lstProyectoUsuario.getSelectedIndex() != -1)
        {
            int auxIndex = lstProyectoUsuario.getSelectedIndex();
            //pasar elementos a usuario (lstUsuario)
            dlmUsuario.addElement(lstProyectoUsuario.getSelectedValue());
            arrayUsuarioId.add(arrayProyectoUsuarioId.get(auxIndex));
            lstUsuario.setModel(dlmUsuario);
            System.out.println("-> Agregado: "+ arrayProyectoUsuarioId.get(auxIndex) +" - "+ lstProyectoUsuario.getSelectedValue());
            
            //quitar elementos de equipo (lstProyectoUsuario)
            arrayProyectoUsuarioId.remove(arrayProyectoUsuarioId.get(auxIndex));
            dlmProyectoUsuario.removeElement(lstProyectoUsuario.getSelectedValue());
            lstProyectoUsuario.setModel(dlmProyectoUsuario);
            
        }
        
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void CargarArbolMetodologia() {
        
        clsMetodologiaDAO metodologiaDAO = new clsMetodologiaDAO();
        Connection conexion;
        Object[][] datosEtapa;
        Object[][] datosEntregable;
        String auxMetodologiaId;        
        
        conexion = clsConexionDS.AbrirConexion();
        auxMetodologiaId = arrayMetodologiaId.get(lstMetodologia.getSelectedIndex());
        datosEtapa =  metodologiaDAO.SeleccionarEtapaEntregableMetodologia (
                    "etapa", 
                    " etapa_id, etapa_nombre", 
                    " metodologia_id='" + auxMetodologiaId + "' ", 
                    conexion
                    );
        
        if( datosEtapa.length > 0)
        {
            for (int i=0; i < datosEtapa.length; i++) 
            {
                //se crea nodo Etapa
                dmtnEtapa = new DefaultMutableTreeNode(datosEtapa[i][1]);
                dmtnMetodologia.add(dmtnEtapa);
                //se obtiene los Entregable
                datosEntregable = metodologiaDAO.SeleccionarEtapaEntregableMetodologia (
                                "entregable", 
                                "entregable_id,entregable_nombre", 
                                " etapa_id='" + datosEtapa[i][0].toString() + "' ", 
                                conexion
                                );
                
                if( datosEntregable.length > 0)
                {
                    for (int j=0; j< datosEntregable.length; j++) 
                    {
                        //intento de colocar en blanco
                        JLabel l = new JLabel((String) datosEntregable[j][0]);     
                        l.setForeground(Color.white);
                        //fin del intento
                        dmtnEntregable = new DefaultMutableTreeNode(l.getText() +
                                " - " + (String) datosEntregable[j][1] );
                        dmtnEtapa.add(dmtnEntregable);
                        
                    }
                }
            }
        }
        clsConexionDS.CerrarConexion(conexion);
        DefaultTreeModel modelo = new DefaultTreeModel(dmtnMetodologia);
        treEntregable.setModel(modelo);
        
    }
    
    
    /**
     *  Carga el JList de metodologias disponibles en la BD.
     *  <p>
     *  Almacena en arrayMetodologiaDescripcion y arrayMetodologiaId
     *  los respectivos datos obtenidos en la BD.
     */
    private void CargarListaMetodologia() {
        
        DefaultListModel dlmMetodologia = new DefaultListModel();
        clsMetodologiaDAO metodologiaDAO = new clsMetodologiaDAO();
        ArrayList<clsMetodologiaDTO> arrayMetodologia;
        String fila[];
        Connection conexion;
        
        dlmMetodologia.removeAllElements();
        fila = new String [3];
        conexion = clsConexionDS.AbrirConexion();
        arrayMetodologia = metodologiaDAO.SeleccionarMetodologia(conexion);
        for(clsMetodologiaDTO m : arrayMetodologia)
        {
            fila[0] = m.getMetodologia_nombre();
            fila[1] = m.getMetodologia_descripcion();
            fila[2] = m.getMetodologia_id();
            dlmMetodologia.addElement(fila[0]);
            arrayMetodologiaDescripcion.add(fila[1]);
            arrayMetodologiaId.add(fila[2]);
        }
        lstMetodologia.setModel(dlmMetodologia);
        clsConexionDS.CerrarConexion(conexion);
    }
    
    /**
     * Carga el JList de usuarios disponibles e la BD con los apellidos
     * y nombres.
     * <p>
     * Almacena el usuario_id en un arrayList.
     */
    private void CargarListaUsuario() {
        
        clsUsuarioDAO usuarioDAO = new clsUsuarioDAO();
        ArrayList<clsUsuarioDTO> arrayUsuario;
        String fila[];
        Connection conexion;
        
        dlmUsuario.removeAllElements();
        fila = new String [3];
        conexion = clsConexionDS.AbrirConexion();
        arrayUsuario = usuarioDAO.SeleccionarUsuario(conexion);
        for(clsUsuarioDTO u : arrayUsuario) 
        {
            fila[0] = u.getUsuario_apellido() + ", " + u.getUsuario_nombre();
            fila[1] = u.getUsuario_id();
            fila[2] = u.getUsuario_jefe_proyecto();            
            if( !fila[0].equals(frmPrincipal.usuarioApellidoNombre) )
            {                
                dlmUsuario.addElement(fila[0]);
                arrayUsuarioId.add(fila[1]);                
            }
        }
        lstUsuario.setModel(dlmUsuario);
        clsConexionDS.CerrarConexion(conexion);
        
    }
    
    /**
     *  Carga el JList de proyectoUsuario (equipo), por defecto
     *  debe aparecer el jefe de proyecto.
     */
    private void CargarListaProyectoUsuario() {
        
        dlmProyectoUsuario.removeAllElements();
        dlmProyectoUsuario.addElement(frmPrincipal.usuarioApellidoNombre);
        arrayProyectoUsuarioId.add(frmPrincipal.usuarioId);
        lstProyectoUsuario.setModel(dlmProyectoUsuario);
        
    }
    
    public void FormularioPrincipal(frmPrincipal xFormulario) {
       
        this.objPrincipal = xFormulario;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearProyecto;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblLiderProyecto;
    private javax.swing.JList<String> lstMetodologia;
    private javax.swing.JList<String> lstProyectoUsuario;
    private javax.swing.JList<String> lstUsuario;
    private javax.swing.JPanel pnlEquipoProyecto;
    private javax.swing.JPanel pnlEquipoProyectoCuerpo;
    private javax.swing.JPanel pnlEquipoProyectoTitlo;
    private javax.swing.JPanel pnlMetodologia;
    private javax.swing.JPanel pnlMetodologiaProyectoCuerpo;
    private javax.swing.JPanel pnlMetodologiaProyectoTitlo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalPadre;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloDatosGenerales;
    private javax.swing.JScrollPane srpPrincipal;
    private com.alee.extended.tree.WebCheckBoxTree treEntregable;
    private javax.swing.JTextArea txtMetodologiaDescripcion;
    private javax.swing.JTextArea txtProyectoDescripcion;
    private javax.swing.JTextField txtProyectoNombre;
    // End of variables declaration//GEN-END:variables
}
