/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import accesodatos.clsProyectoDAO;
import conexion.clsConexionDS;
import global.clsTablasRender;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import transferenciadatos.clsProyectoDTO;

/**
 *
 * @author Kevin
 */
public class frmProyectoArchivado extends javax.swing.JPanel {
    
    Connection conexion;
    String proyectoId;
    /**
     * Creates new form frmProyectoArchivado
     */
    public frmProyectoArchivado() {
        initComponents();
        conexion = clsConexionDS.AbrirConexion();
        CargarTablaProyectoArchivado();
        clsConexionDS.CerrarConexion(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlIzquierda = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlProyectos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchivado = new javax.swing.JTable();
        btnActivar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnlIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        pnlIzquierda.setPreferredSize(new java.awt.Dimension(500, 308));
        pnlIzquierda.setLayout(new java.awt.BorderLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(711, 110));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(179, 229, 252));
        jPanel2.setPreferredSize(new java.awt.Dimension(671, 100));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 22)); // NOI18N
        jLabel2.setText("PROYECTOS ARCHIVADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        pnlTitulo.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTitulo.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlIzquierda.add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlProyectos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProyectos.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(630, 200));

        tblArchivado.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        tblArchivado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Proyecto", "Estado", "Descripcion"
            }
        ));
        tblArchivado.setMinimumSize(new java.awt.Dimension(600, 200));
        tblArchivado.setPreferredSize(new java.awt.Dimension(620, 150));
        tblArchivado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArchivadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArchivado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        pnlProyectos.add(jScrollPane1, gridBagConstraints);

        btnActivar.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnActivar.setText("Activar Proyecto");
        btnActivar.setEnabled(false);
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.insets = new java.awt.Insets(35, 24, 35, 0);
        pnlProyectos.add(btnActivar, gridBagConstraints);

        jLabel1.setText("                                                                                                                                            ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlProyectos.add(jLabel1, gridBagConstraints);

        pnlIzquierda.add(pnlProyectos, java.awt.BorderLayout.CENTER);

        add(pnlIzquierda, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblArchivadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArchivadoMouseClicked
        
        int reg;
        
        DefaultTableModel dtm = new DefaultTableModel();
        reg = tblArchivado.getSelectedRow();
        if(reg == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro");
        }
        else
        {
            dtm = (DefaultTableModel)tblArchivado.getModel();
            proyectoId = ((String) dtm.getValueAt(reg, 0)); 
            btnActivar.setEnabled(true);             
        }
        
    }//GEN-LAST:event_tblArchivadoMouseClicked

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        
        String estado;
        clsProyectoDTO proyectoDTO;
        clsProyectoDAO proyectoDAO = new clsProyectoDAO();
        
        estado = "activo";
        conexion = clsConexionDS.AbrirConexion();
        proyectoDTO = new clsProyectoDTO (
                        proyectoId,
                        estado,
                        "",
                        "",
                        "",
                        ""
                    );
        proyectoDAO.ActualizarEstadoProyecto(proyectoDTO, conexion);
        CargarTablaProyectoArchivado();
        btnActivar.setEnabled(false);
        clsConexionDS.CerrarConexion(conexion);
        
    }//GEN-LAST:event_btnActivarActionPerformed

    
    private void CargarTablaProyectoArchivado() {
        
        String[] titulos = {"id", "Nombre", "Estado", "Descripcion Estado", "Fecha"};
        String[] fila;        
        clsProyectoDAO proyectoDAO;
        ArrayList<clsProyectoDTO> arrayProyectoDTO;        
        DefaultTableModel dtmArchivado;
        
        fila = new String[6];
        dtmArchivado = new DefaultTableModel(null,titulos) {        
            @Override
            public boolean isCellEditable(int rowIndex,int columnIndex){return false;}               
        };        
        
        proyectoDAO = new clsProyectoDAO();
        arrayProyectoDTO = proyectoDAO.SeleccionarProyecto(conexion);
        
        for(clsProyectoDTO p : arrayProyectoDTO)
        {
            fila[0] = p.getProyecto_id();
            fila[1] = p.getProyecto_nombre();
            fila[2] = p.getProyecto_estado();
            fila[3] = p.getProyecto_estado_descripcion();
            fila[4] = p.getProyecto_fecha_creacion();  
            
            if( !fila[2].equals("activo") )
            {
                dtmArchivado.addRow(fila);
            }                    
        }
        
        tblArchivado.setModel(dtmArchivado);
        tblArchivado.removeColumn(tblArchivado.getColumnModel().getColumn(0));
        TableCellRenderer tcr =  tblArchivado.getTableHeader().getDefaultRenderer();
        clsTablasRender.miRender mr = new clsTablasRender.miRender(tcr);
        mr.getTableCellRendererComponent(tblArchivado, fila, true, true, WIDTH, 1);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlIzquierda;
    private javax.swing.JPanel pnlProyectos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblArchivado;
    // End of variables declaration//GEN-END:variables
}
