/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistacontrol;

import java.awt.Font;

/**
 *
 * @author Usuario
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private boolean usuarioJefeProyecto;
    public static String usuarioApellidoNombre;
    public static String usuarioId;
    public static String proyectoId;
    private static final Font FUENTE_DEFAULT = new Font("Droid Sans", Font.PLAIN, 12);
    
    //El constructor recibe los datos de jefe de proyecto y nombres del usuario
    //para que puedan ser trabajados por todo el sistema.
    public frmPrincipal(boolean xUsuarioJefeProyecto, String xUsuarioNombreApellido, 
            String xUsuarioId) {
       
        initComponents();
        
        usuarioJefeProyecto = xUsuarioJefeProyecto;
        usuarioApellidoNombre = xUsuarioNombreApellido;
        usuarioId = xUsuarioId;
        System.out.println(usuarioJefeProyecto);
        lblUsuario.setFont(FUENTE_DEFAULT);
        lblUsuario.setText(usuarioApellidoNombre);  
        AbrirModalProyectos();
        
    }

    public frmPrincipal() {
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpEscritorio = new javax.swing.JDesktopPane();
        pnlBot = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        mbrPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnuProyectos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuSolicitudCambio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestor de Configuración de Proyectos");
        setPreferredSize(new java.awt.Dimension(1150, 700));

        dtpEscritorio.setLayout(new java.awt.BorderLayout());

        pnlBot.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout pnlBotLayout = new javax.swing.GroupLayout(pnlBot);
        pnlBot.setLayout(pnlBotLayout);
        pnlBotLayout.setHorizontalGroup(
            pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        pnlBotLayout.setVerticalGroup(
            pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mbrPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setContentAreaFilled(false);
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jMenu1.setIconTextGap(0);
        mbrPrincipal.add(jMenu1);

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/archive.png"))); // NOI18N
        mnuArchivo.setText("Archivo");
        mnuArchivo.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        mniSalir.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        mniSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/exit-to-app.png"))); // NOI18N
        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mniSalir);

        mbrPrincipal.add(mnuArchivo);

        mnuProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/clipboard-text.png"))); // NOI18N
        mnuProyectos.setText("Proyectos");
        mnuProyectos.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jMenuItem3.setText("Mis Proyectos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuProyectos.add(jMenuItem3);

        jMenuItem1.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jMenuItem1.setText("Proyectos Archivados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuProyectos.add(jMenuItem1);

        mbrPrincipal.add(mnuProyectos);

        mnuSolicitudCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/x24/account-convert.png"))); // NOI18N
        mnuSolicitudCambio.setText("Solicitud de Cambio");
        mnuSolicitudCambio.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jMenuItem2.setText("Solicitudes de Cambio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuSolicitudCambio.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jMenuItem4.setText("Solicitudes de Cambio Derivadas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuSolicitudCambio.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jMenuItem5.setText("Solicitudes Finalizadas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuSolicitudCambio.add(jMenuItem5);

        mbrPrincipal.add(mnuSolicitudCambio);

        setJMenuBar(mbrPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnlBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dtpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_mniSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        AbrirModalProyectos();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        AbrirModalSolicitudCambio();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        AbrirModalSolicitudCambioDerivada();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        AbrirModalProyectoArchivado();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        AbrirModalCambioFinalizado();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    
    
    public void AbrirModalProyectoArchivado() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmProyectoArchivado proyectoArchivado = new frmProyectoArchivado();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (proyectoArchivado.isShowing()) 
        {
            proyectoArchivado.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(proyectoArchivado);
            proyectoArchivado.setBounds(0,0,x, y);
            proyectoArchivado.setVisible(true);            
        }
        
    }
    
    public void AbrirModalSolicitudCambio() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmCambio cambio = new frmCambio();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (cambio.isShowing()) 
        {
            cambio.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(cambio);
            cambio.setBounds(0,0,x, y);
            cambio.setVisible(true);            
        }
        
    }
    
    public void AbrirModalCambioFinalizado() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmCambioFinalizado cambioFinalizado = new frmCambioFinalizado();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (cambioFinalizado.isShowing()) 
        {
            cambioFinalizado.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(cambioFinalizado);
            cambioFinalizado.setBounds(0,0,x, y);
            cambioFinalizado.setVisible(true);            
        }
        
    }
    
    public void AbrirModalSolicitudCambioDerivada() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmCambioDerivado cambioDerivado = new frmCambioDerivado();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (cambioDerivado.isShowing()) 
        {
            cambioDerivado.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(cambioDerivado);
            cambioDerivado.setBounds(0,0,x, y);
            cambioDerivado.setVisible(true);            
        }
        
    }
    
    /**
     * Abre la vista principal de proyectos.
     */
    public void AbrirModalProyectos() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmProyectos proyectos = new frmProyectos();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (proyectos.isShowing()) 
        {
            proyectos.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(proyectos);
            proyectos.setBounds(0,0,x, y);
            proyectos.FormularioPrincipal(this);
            proyectos.setVisible(true);            
        }
        
    }
    
    public void AbrirModalAdministrarProyecto() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmAdministrarProyecto administrarProyectos = new frmAdministrarProyecto();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (administrarProyectos.isShowing()) 
        {
            administrarProyectos.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(administrarProyectos);
            administrarProyectos.setBounds(0,0,x, y);
            administrarProyectos.setVisible(true);            
        }
        
    }
    
    public void AbrirModalNuevoProyecto() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmNuevoProyecto nuevoProyectos = new frmNuevoProyecto();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (nuevoProyectos.isShowing()) 
        {
            nuevoProyectos.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(nuevoProyectos);
            nuevoProyectos.setBounds(0,0,x, y);
            nuevoProyectos.FormularioPrincipal(this);
            nuevoProyectos.setVisible(true);            
        }
        
    }
    
    /**
     *  Este método abre la ventana modal frmConfigurarEntregable desde frmPrincipal
     */
    public void AbrirModalConfigurarEntregable() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmConfigurarEntregable configurarProyecto = new frmConfigurarEntregable();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (configurarProyecto.isShowing()) 
        {
            configurarProyecto.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(configurarProyecto);
            configurarProyecto.setBounds(0,0,x, y);
            configurarProyecto.setVisible(true);            
        }
        
    }
    
    public void AbrirModalEditarProyecto() {
        
        int x = (dtpEscritorio.getWidth());
        int y = (dtpEscritorio.getHeight()); 
        frmEditarProyecto editarProyecto = new frmEditarProyecto();
        dtpEscritorio.removeAll();
        dtpEscritorio.updateUI();
        if (editarProyecto.isShowing()) 
        {
            editarProyecto.setLocation(x, y);
        } 
        else 
        {
            dtpEscritorio.add(editarProyecto);
            editarProyecto.setBounds(0,0,x, y);
            editarProyecto.FormularioPrincipal(this);
            editarProyecto.setVisible(true);            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dtpEscritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar mbrPrincipal;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuProyectos;
    private javax.swing.JMenu mnuSolicitudCambio;
    private javax.swing.JPanel pnlBot;
    // End of variables declaration//GEN-END:variables
}
